name: wawu_mobile
description: "A Platform for the African Creative"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

#---------------------------- PACKAGES ----------------------#
dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  flutter_native_splash: ^2.4.0
  provider: ^6.1.2
  http: ^1.3.0
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  voice_message_package: ^2.2.1
  record: ^5.2.1
  path_provider: ^2.1.5
  just_audio: ^0.9.46
  dio: ^5.8.0+1
  percent_indicator: ^4.2.4
  font_awesome_flutter: ^10.8.0
  flutter_markdown: ^0.7.6+2
  share_plus: ^10.1.4
  pluto_grid: ^8.0.0

flutter_native_splash:
  color: "#ffffff"  # Change this to your desired background color
  image: assets/logo/logo.png  # Path to your splash image
  android: true
  ios: true
  web: false
  android_gravity: center
  android_12:
    color: "#ffffff"
    image: assets/logo/logo.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#121212"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/onboarding_images/
    - assets/images/svg/
    - assets/images/roles/
    - assets/images/other/
    - assets/images/section/