name: wawu_mobile
description: "A Platform for the African Creative"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

#---------------------------- PACKAGES ----------------------#
dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  flutter_native_splash: ^2.4.0
  timeago: ^3.7.1
  flutter_local_notifications: ^19.2.1
  pusher_channels_flutter: ^2.5.0
  file_picker: ^10.1.9
  http_parser: ^4.1.2
  provider: ^6.1.2
  collection: ^1.19.1
  http: ^1.3.0
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  voice_message_package: ^2.2.1
  record: ^5.2.1
  path_provider: ^2.1.5
  just_audio: ^0.9.46
  dio: ^5.8.0+1
  percent_indicator: ^4.2.4
  font_awesome_flutter: ^10.8.0
  flutter_markdown: ^0.7.6+2
  share_plus: ^10.1.4
  pluto_grid: ^8.0.0
  pusher_client_fixed: ^0.0.5
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.4
  equatable: ^2.0.7

flutter_native_splash:
  color: "#ffffff"  # Change this to your desired background color
  android: true
  ios: true
  web: false
  image: assets/logo/logo_white.png
  android_12:
    color: "#ffffff"
    color_dark: "#121212"
    image_dark: assets/logo/logo_black.png
    image: assets/logo/logo_white.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#121212"
  # Prevent stretching or filling (this avoids cropping)
  # Android-specific gravity (optional, tweak if needed)
  android_gravity: fill  # Options: center, fill, top, etc.
  # iOS-specific content mode (optional, tweak if needed)
  ios_content_mode: center

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/logo/
    - assets/images/onboarding_images/
    - assets/images/svg/
    - assets/images/roles/
    - assets/images/other/
    - assets/images/section/

