name: wawu_mobile
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

#---------------------------- PACKAGES ----------------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0

# Utility Packages
  provider: ^6.1.2
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.2


flutter_native_splash:
  color: "#ffffff"  # Change this to your desired background color
  image: assets/logo/logo.png  # Path to your splash image
  android: true
  ios: true


cupertino_icons: ^1.0.8
iconsax_plus: ^1.0.0
iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts
    - assets/icons
    - assets/logo
    - assets/images/onboarding_images/

