name: Flutter Android CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'master'
        cache: true

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build debug APK
      run: flutter build apk --debug

    - name: Build release APK
      run: flutter build apk --release

    - name: Rename APKs
      run: |
        cp build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/wawu-debug.apk
        cp build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/wawu-release.apk

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/wawu-debug.apk
          build/app/outputs/flutter-apk/wawu-release.apk
        name: Release ${{ github.ref_name }}
        body: |
          ## What's Changed
          - Debug APK for testing and debugging
          - Release APK for production use
          
          ## Installation
          Download the debug APK for testing or release APK for production use.
        draft: false
        prerelease: false
