name: iOS Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        
    - name: Create .env file
      run: |
        echo "PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}" > .env
        echo "PUSHER_CLUSTER=${{ secrets.PUSHER_CLUSTER }}" >> .env
        
    - name: Install dependencies
      run: flutter pub get
      
    # - name: Run tests
    #   run: flutter test
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Install Fastlane
      run: gem install fastlane
      
    - name: Setup Git credentials for Match
      run: |
        git config --global user.email "ci@github.com"
        git config --global user.name "GitHub Actions"
        
    # Fix iOS deployment target before building
    - name: Fix iOS deployment target
      run: |
        # Update Podfile
        sed -i '' 's/# platform :ios, '\''[0-9.]*'\''/platform :ios, '\''13.0'\''/g' ios/Podfile
        sed -i '' 's/platform :ios, '\''[0-9.]*'\''/platform :ios, '\''13.0'\''/g' ios/Podfile
        
        # If no platform line exists, add it
        if ! grep -q "platform :ios" ios/Podfile; then
          sed -i '' '1i\
        platform :ios, '\''13.0'\''
        ' ios/Podfile
                fi
        
        # Update Flutter framework info
        /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 13.0" ios/Flutter/AppFrameworkInfo.plist || true
        
        # Update Runner Info.plist
        /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 13.0" ios/Runner/Info.plist || true
        
    - name: Deploy to TestFlight
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_TOKEN: ${{ secrets.MATCH_GIT_TOKEN }}
        FASTLANE_SKIP_UPDATE_CHECK: true
        FASTLANE_HIDE_GITHUB_ISSUES: true
        FASTLANE_DISABLE_ANIMATION: true
        MATCH_KEYCHAIN_NAME: signing_keychain
        MATCH_KEYCHAIN_PASSWORD: temp_password
        FL_UNLOCK_KEYCHAIN_PASSWORD: temp_password
        MATCH_TYPE: appstore
        MATCH_READONLY: true
        MATCH_STORAGE_MODE: git
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_TOKEN }}
        MATCH_SKIP_CONFIRMATION: true
        MATCH_VERBOSE: true
      run: |
        cd ios
        echo "$APP_STORE_CONNECT_API_KEY" | base64 --decode > AuthKey.p8
        fastlane beta
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: ios/build/ios/ipa/*.ipa
        retention-days: 30
      if: always()
        
    - name: Clean up
      if: always()
      run: |
        rm -f ios/AuthKey.p8
        # Clean up any remaining keychains
        security delete-keychain signing_keychain || true